/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectomarcos;

import Controlador.PersonalController;
import java.awt.Color;
import javax.swing.JOptionPane;

public class AñadirPersonal extends javax.swing.JFrame {
    private Personal personalFrame; // Referencia al JFrame principal
    private PersonalController personalController = new PersonalController();
    
    /**
     * Creates new form AñadirPersonal2
     */
    public AñadirPersonal() {
        initComponents();
    }
    
    
    public AñadirPersonal(Personal parent) {
        this.personalFrame = parent;
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jp3 = new javax.swing.JPanel();
        jp4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCancelarPer2 = new javax.swing.JButton();
        btnAñadirPer = new javax.swing.JButton();
        txtNomPer = new javax.swing.JTextField();
        txtEmailPer = new javax.swing.JTextField();
        txtTelePer = new javax.swing.JTextField();
        cmbRol = new javax.swing.JComboBox<>();
        txtContra = new javax.swing.JTextField();
        btnPersonal = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnSalir2 = new javax.swing.JButton();
        btnMasVendidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(111, 67, 57));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono_menu.png"))); // NOI18N

        jp3.setBackground(new java.awt.Color(253, 231, 195));

        jp4.setBackground(new java.awt.Color(253, 231, 195));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(111, 67, 57));
        jLabel9.setText("Añadir Personal");

        jPanel1.setBackground(new java.awt.Color(250, 235, 216));

        btnCancelarPer2.setBackground(new java.awt.Color(247, 243, 237));
        btnCancelarPer2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelarPer2.setForeground(new java.awt.Color(111, 67, 57));
        btnCancelarPer2.setText("Cancelar");
        btnCancelarPer2.setBorder(null);
        btnCancelarPer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPer2ActionPerformed(evt);
            }
        });

        btnAñadirPer.setBackground(new java.awt.Color(235, 91, 91));
        btnAñadirPer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAñadirPer.setForeground(new java.awt.Color(253, 231, 195));
        btnAñadirPer.setText("Añadir");
        btnAñadirPer.setBorder(null);
        btnAñadirPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirPerActionPerformed(evt);
            }
        });

        txtNomPer.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNomPer.setForeground(new java.awt.Color(111, 67, 57));
        txtNomPer.setText("   Nombre");
        txtNomPer.setBorder(null);
        txtNomPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomPerActionPerformed(evt);
            }
        });

        txtEmailPer.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtEmailPer.setForeground(new java.awt.Color(111, 67, 57));
        txtEmailPer.setText("   Email");
        txtEmailPer.setBorder(null);

        txtTelePer.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtTelePer.setForeground(new java.awt.Color(111, 67, 57));
        txtTelePer.setText("   Telefono");
        txtTelePer.setBorder(null);

        cmbRol.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbRol.setForeground(new java.awt.Color(111, 67, 57));
        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Vendedor" }));
        cmbRol.setBorder(null);
        cmbRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRolActionPerformed(evt);
            }
        });

        txtContra.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtContra.setForeground(new java.awt.Color(111, 67, 57));
        txtContra.setText("  Contraseña");
        txtContra.setBorder(null);
        txtContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTelePer)
                    .addComponent(txtEmailPer)
                    .addComponent(txtNomPer)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnCancelarPer2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(btnAñadirPer, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addComponent(cmbRol, 0, 382, Short.MAX_VALUE)
                    .addComponent(txtContra))
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(txtNomPer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtEmailPer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTelePer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAñadirPer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarPer2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        txtNomPer.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtNomPer.getText().trim().equals("Nombre")) {
                    txtNomPer.setText("");
                    txtNomPer.setForeground(java.awt.Color.BLACK);
                }
            }
            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtNomPer.getText().trim().isEmpty()) {
                    txtNomPer.setText("   Nombre");
                    txtNomPer.setForeground(new java.awt.Color(111, 67, 57));
                }
            }
        });
        txtEmailPer.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtEmailPer.getText().trim().equals("Email")) {
                    txtEmailPer.setText("");
                    txtEmailPer.setForeground(Color.BLACK);
                }
            }
            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtEmailPer.getText().trim().isEmpty()) {
                    txtEmailPer.setText("   Email");
                    txtEmailPer.setForeground(new java.awt.Color(111, 67, 57));
                }
            }
        });
        txtTelePer.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtTelePer.getText().trim().equals("Telefono")) {
                    txtTelePer.setText("");
                    txtTelePer.setForeground(Color.BLACK);
                }
            }
            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtTelePer.getText().trim().isEmpty()) {
                    txtTelePer.setText("   Telefono");
                    txtTelePer.setForeground(new java.awt.Color(111, 67, 57));
                }
            }
        });
        txtContra.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (txtContra.getText().trim().equals("Contraseña")) {
                    txtContra.setText("");
                    txtContra.setForeground(Color.BLACK);
                }
            }
            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (txtContra.getText().trim().isEmpty()) {
                    txtContra.setText(" Contraseña");
                    txtContra.setForeground(new java.awt.Color(111, 67, 57));
                }
            }
        });

        javax.swing.GroupLayout jp4Layout = new javax.swing.GroupLayout(jp4);
        jp4.setLayout(jp4Layout);
        jp4Layout.setHorizontalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jp4Layout.setVerticalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp3Layout = new javax.swing.GroupLayout(jp3);
        jp3.setLayout(jp3Layout);
        jp3Layout.setHorizontalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
            .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp3Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(jp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );
        jp3Layout.setVerticalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
            .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jp4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        btnPersonal.setBackground(new java.awt.Color(111, 67, 57));
        btnPersonal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPersonal.setForeground(new java.awt.Color(253, 231, 195));
        btnPersonal.setText("Personal");
        btnPersonal.setBorder(null);
        btnPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalActionPerformed(evt);
            }
        });

        btnProductos.setBackground(new java.awt.Color(111, 67, 57));
        btnProductos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(253, 231, 195));
        btnProductos.setText("Productos");
        btnProductos.setBorder(null);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnPedidos.setBackground(new java.awt.Color(111, 67, 57));
        btnPedidos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPedidos.setForeground(new java.awt.Color(253, 231, 195));
        btnPedidos.setText("Pedidos");
        btnPedidos.setBorder(null);
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });

        btnSalir2.setBackground(new java.awt.Color(246, 199, 129));
        btnSalir2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSalir2.setForeground(new java.awt.Color(253, 231, 195));
        btnSalir2.setText("Salir");
        btnSalir2.setBorder(null);
        btnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir2ActionPerformed(evt);
            }
        });

        btnMasVendidos.setBackground(new java.awt.Color(111, 67, 57));
        btnMasVendidos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnMasVendidos.setForeground(new java.awt.Color(253, 231, 195));
        btnMasVendidos.setText("Mas vendidos");
        btnMasVendidos.setBorder(null);
        btnMasVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasVendidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPersonal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMasVendidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPedidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnMasVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addComponent(jp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalActionPerformed
        Personal PersonalFrame = new Personal();
        PersonalFrame.setVisible(true);
        PersonalFrame.pack();
        PersonalFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnPersonalActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        ProductoFrame ProductoFrame = new ProductoFrame();
        ProductoFrame.setVisible(true);
        ProductoFrame.pack();
        ProductoFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        PedidoFrame PedidoFrame = new PedidoFrame();
        PedidoFrame.setVisible(true);
        PedidoFrame.pack();
        PedidoFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnCancelarPer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPer2ActionPerformed
        Personal PersonalFrame = new Personal();
        PersonalFrame.setVisible(true);
        PersonalFrame.pack();
        PersonalFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnCancelarPer2ActionPerformed

    private void btnAñadirPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirPerActionPerformed
        try {
        String nombre = txtNomPer.getText().trim(); // Elimina espacios al inicio y final
        String email = txtEmailPer.getText().trim();
        String contrasena = txtContra.getText().trim();
        Integer telefono = txtTelePer.getText().isEmpty() ? null : Integer.parseInt(txtTelePer.getText().trim());
        String rol = (String) cmbRol.getSelectedItem();

        if (contrasena == null || contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La contraseña no puede estar vacía.");
            return;
        }

        // Intentar agregar el personal
        if (personalController.agregarPersonal(generatePersonalId(), nombre, email, contrasena, telefono, rol)) {
            JOptionPane.showMessageDialog(this, "Personal añadido exitosamente.");
            
            // Redirigir a la ventana de la tabla (o lista de personal)
            personalFrame.actualizarTabla();  // Si necesitas actualizar la tabla

            // Mostrar la ventana de personal
            Personal PersonalFrame = new Personal();
            PersonalFrame.setVisible(true);
            PersonalFrame.pack();
            PersonalFrame.setLocationRelativeTo(null);

            // Cerrar la ventana actual
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al añadir personal (verifica la contraseña). La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula, una letra y un carácter especial.");
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Teléfono debe ser un número válido.");
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Ocurrió un error: " + ex.getMessage());
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btnAñadirPerActionPerformed

    private void txtNomPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomPerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomPerActionPerformed

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnSalir2ActionPerformed

    private void btnMasVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasVendidosActionPerformed
        Menu MenuFrame = new Menu();
        MenuFrame.setVisible(true);
        MenuFrame.pack();
        MenuFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnMasVendidosActionPerformed

    private void cmbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRolActionPerformed

    private void txtContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraActionPerformed

    
    private String generatePersonalId() {
        String ultimoId = personalController.obtenerUltimoPersonalId(); // Añade este método en PersonalController
        int numero = Integer.parseInt(ultimoId.replace("P", "")) + 1;
        return "P" + String.format("%03d", numero);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirPer;
    private javax.swing.JButton btnCancelarPer2;
    private javax.swing.JButton btnMasVendidos;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnPersonal;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnSalir2;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jp3;
    private javax.swing.JPanel jp4;
    private javax.swing.JTextField txtContra;
    private javax.swing.JTextField txtEmailPer;
    private javax.swing.JTextField txtNomPer;
    private javax.swing.JTextField txtTelePer;
    // End of variables declaration//GEN-END:variables
}
