/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectomarcos;


import Controlador.ProductoController;
import javax.swing.JOptionPane;

public class EditarProducto extends javax.swing.JFrame {
    private ProductoController productoController;
    private String productoId;
    private ProductoFrame productoFrame;
    public EditarProducto() {
        initComponents();
    }
    public EditarProducto( String productoId, String nombre, String estado, double precio, int stock, String categoria) {
        this.productoId = productoId;
        initComponents();
        txtNomPro2.setText(nombre);
        cmbCatePro.setSelectedItem(categoria);
        txtPrecioPro2.setText(String.format("%.2f", precio));
        txtStockPro2.setText(String.valueOf(stock));  
        cmbEstadoPro.setSelectedItem(estado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jp3 = new javax.swing.JPanel();
        jp4 = new javax.swing.JPanel();
        txtCatePro2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtNomPro2 = new javax.swing.JTextField();
        cmbCatePro = new javax.swing.JComboBox<>();
        txtPrecioPro2 = new javax.swing.JTextField();
        txtStockPro2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbEstadoPro = new javax.swing.JComboBox<>();
        btnCancelarPro2 = new javax.swing.JButton();
        btnActuaPro2 = new javax.swing.JButton();
        btnPersonal = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnSalir2 = new javax.swing.JButton();
        btnMasVendidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(111, 67, 57));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono_menu.png"))); // NOI18N

        jp3.setBackground(new java.awt.Color(253, 231, 195));

        jp4.setBackground(new java.awt.Color(253, 231, 195));

        txtCatePro2.setBackground(new java.awt.Color(253, 231, 195));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(111, 67, 57));
        jLabel9.setText("Editar Producto");

        txtNomPro2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNomPro2.setBorder(null);

        cmbCatePro.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbCatePro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tortas", "Postres", "Galletas" }));
        cmbCatePro.setBorder(null);

        txtPrecioPro2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPrecioPro2.setBorder(null);

        txtStockPro2.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(111, 67, 57));
        jLabel7.setText("Nombre");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(111, 67, 57));
        jLabel8.setText("Categoria");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(111, 67, 57));
        jLabel10.setText("Precio");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(111, 67, 57));
        jLabel11.setText("Estado");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(111, 67, 57));
        jLabel12.setText("Stock");

        cmbEstadoPro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo", " " }));
        cmbEstadoPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout txtCatePro2Layout = new javax.swing.GroupLayout(txtCatePro2);
        txtCatePro2.setLayout(txtCatePro2Layout);
        txtCatePro2Layout.setHorizontalGroup(
            txtCatePro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtCatePro2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(txtCatePro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(txtCatePro2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(136, 136, 136))
                    .addGroup(txtCatePro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPrecioPro2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                        .addComponent(txtStockPro2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel11)
                        .addComponent(cmbCatePro, 0, 247, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addComponent(txtNomPro2, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel12)
                        .addComponent(cmbEstadoPro, 0, 247, Short.MAX_VALUE)))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        txtCatePro2Layout.setVerticalGroup(
            txtCatePro2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtCatePro2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(3, 3, 3)
                .addComponent(txtNomPro2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbCatePro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecioPro2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStockPro2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbEstadoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp4Layout = new javax.swing.GroupLayout(jp4);
        jp4.setLayout(jp4Layout);
        jp4Layout.setHorizontalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCatePro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jp4Layout.setVerticalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addComponent(txtCatePro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancelarPro2.setBackground(new java.awt.Color(247, 243, 237));
        btnCancelarPro2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelarPro2.setForeground(new java.awt.Color(111, 67, 57));
        btnCancelarPro2.setText("Cancelar");
        btnCancelarPro2.setBorder(null);
        btnCancelarPro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPro2ActionPerformed(evt);
            }
        });

        btnActuaPro2.setBackground(new java.awt.Color(235, 91, 91));
        btnActuaPro2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnActuaPro2.setForeground(new java.awt.Color(253, 231, 195));
        btnActuaPro2.setText("Actualizar");
        btnActuaPro2.setBorder(null);
        btnActuaPro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActuaPro2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp3Layout = new javax.swing.GroupLayout(jp3);
        jp3.setLayout(jp3Layout);
        jp3Layout.setHorizontalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActuaPro2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(btnCancelarPro2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
            .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp3Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(jp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jp3Layout.setVerticalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActuaPro2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarPro2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(60, Short.MAX_VALUE)))
        );

        btnPersonal.setBackground(new java.awt.Color(111, 67, 57));
        btnPersonal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPersonal.setForeground(new java.awt.Color(253, 231, 195));
        btnPersonal.setText("Personal");
        btnPersonal.setBorder(null);
        btnPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalActionPerformed(evt);
            }
        });

        btnProductos.setBackground(new java.awt.Color(111, 67, 57));
        btnProductos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(253, 231, 195));
        btnProductos.setText("Productos");
        btnProductos.setBorder(null);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnPedidos.setBackground(new java.awt.Color(111, 67, 57));
        btnPedidos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPedidos.setForeground(new java.awt.Color(253, 231, 195));
        btnPedidos.setText("Pedidos");
        btnPedidos.setBorder(null);
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });

        btnSalir2.setBackground(new java.awt.Color(246, 199, 129));
        btnSalir2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSalir2.setForeground(new java.awt.Color(253, 231, 195));
        btnSalir2.setText("Salir");
        btnSalir2.setBorder(null);
        btnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir2ActionPerformed(evt);
            }
        });

        btnMasVendidos.setBackground(new java.awt.Color(111, 67, 57));
        btnMasVendidos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnMasVendidos.setForeground(new java.awt.Color(253, 231, 195));
        btnMasVendidos.setText("Ranking");
        btnMasVendidos.setBorder(null);
        btnMasVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasVendidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPersonal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMasVendidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPedidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jp3, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnMasVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(btnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addComponent(jp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalActionPerformed
        Personal PersonalFrame = new Personal();
        PersonalFrame.setVisible(true);
        PersonalFrame.pack();
        PersonalFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnPersonalActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        ProductoFrame ProductoFrame = new ProductoFrame();
        ProductoFrame.setVisible(true);
        ProductoFrame.pack();
        ProductoFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        PedidoFrame PedidoFrame = new PedidoFrame();
        PedidoFrame.setVisible(true);
        PedidoFrame.pack();
        PedidoFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnSalir2ActionPerformed

    private void btnMasVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasVendidosActionPerformed
        Menu MenuFrame = new Menu();
        MenuFrame.setVisible(true);
        MenuFrame.pack();
        MenuFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnMasVendidosActionPerformed

    private void btnActuaPro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActuaPro2ActionPerformed
        ProductoController pController= new ProductoController();
        try {
            String nombre = txtNomPro2.getText().trim();
            String categoria = (String) cmbCatePro.getSelectedItem();
            double precio = Double.parseDouble(txtPrecioPro2.getText().trim());
            int stock = Integer.parseInt(txtStockPro2.getText().trim());
            String estado = (String) cmbEstadoPro.getSelectedItem();
           
        if (pController.editarProducto(productoId, nombre, estado, precio, stock, categoria)) {
            JOptionPane.showMessageDialog(this, "Producto actualizado correctamente.");
            ProductoFrame ProductoFrame = new ProductoFrame();
            ProductoFrame.setVisible(true);
            ProductoFrame.pack();
            ProductoFrame.setLocationRelativeTo(null);
            this.dispose();
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar producto.");
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnActuaPro2ActionPerformed

    private void btnCancelarPro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPro2ActionPerformed
        ProductoFrame ProductoFrame = new ProductoFrame();
        ProductoFrame.setVisible(true);
        ProductoFrame.pack();
        ProductoFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnCancelarPro2ActionPerformed

    private void cmbEstadoProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoProActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActuaPro2;
    private javax.swing.JButton btnCancelarPro2;
    private javax.swing.JButton btnMasVendidos;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnPersonal;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnSalir2;
    private javax.swing.JComboBox<String> cmbCatePro;
    private javax.swing.JComboBox<String> cmbEstadoPro;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jp3;
    private javax.swing.JPanel jp4;
    private javax.swing.JPanel txtCatePro2;
    private javax.swing.JTextField txtNomPro2;
    private javax.swing.JTextField txtPrecioPro2;
    private javax.swing.JTextField txtStockPro2;
    // End of variables declaration//GEN-END:variables
}
