/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectomarcos;

import Controlador.PersonalController;
import javax.swing.JOptionPane;

public class EditarPersonal extends javax.swing.JFrame {
    private Personal personalFrame; // Referencia al JFrame principal
    private String personalId;
    private PersonalController personalController = new PersonalController();
    
   
    public EditarPersonal() {
        initComponents();
    }
    
    public EditarPersonal(Personal parent, String personalId, String nombre, String email, Integer telefono, String rol) {
        this.personalFrame = parent;
        this.personalId = personalId;
        initComponents();
        txtNomPer.setText(nombre);
        txtEmailPer.setText(email);
        txtTelefPer.setText(telefono != null ? telefono.toString() : "");
        cmbRol.setSelectedItem(rol);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jp3 = new javax.swing.JPanel();
        jp4 = new javax.swing.JPanel();
        jp5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnCancelarPer = new javax.swing.JButton();
        btnActualizarPer = new javax.swing.JButton();
        txtNomPer = new javax.swing.JTextField();
        txtEmailPer = new javax.swing.JTextField();
        txtTelefPer = new javax.swing.JTextField();
        txtContra = new javax.swing.JTextField();
        cmbRol = new javax.swing.JComboBox<>();
        btnPersonal = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnSalir2 = new javax.swing.JButton();
        btnMasVendidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(111, 67, 57));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono_menu.png"))); // NOI18N

        jp3.setBackground(new java.awt.Color(253, 231, 195));

        jp4.setBackground(new java.awt.Color(253, 231, 195));

        jp5.setBackground(new java.awt.Color(253, 231, 195));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(111, 67, 57));
        jLabel9.setText("Editar Personal");

        jPanel1.setBackground(new java.awt.Color(250, 235, 216));

        btnCancelarPer.setBackground(new java.awt.Color(247, 243, 237));
        btnCancelarPer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelarPer.setForeground(new java.awt.Color(111, 67, 57));
        btnCancelarPer.setText("Cancelar");
        btnCancelarPer.setBorder(null);
        btnCancelarPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPerActionPerformed(evt);
            }
        });

        btnActualizarPer.setBackground(new java.awt.Color(235, 91, 91));
        btnActualizarPer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnActualizarPer.setForeground(new java.awt.Color(253, 231, 195));
        btnActualizarPer.setText("Actualizar");
        btnActualizarPer.setBorder(null);
        btnActualizarPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPerActionPerformed(evt);
            }
        });

        txtNomPer.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNomPer.setForeground(new java.awt.Color(111, 67, 57));
        txtNomPer.setText("   Nombre");
        txtNomPer.setBorder(null);
        txtNomPer.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                txtNomPerMouseDragged(evt);
            }
        });
        txtNomPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomPerActionPerformed(evt);
            }
        });

        txtEmailPer.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtEmailPer.setForeground(new java.awt.Color(111, 67, 57));
        txtEmailPer.setText("   Email");
        txtEmailPer.setBorder(null);
        txtEmailPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailPerActionPerformed(evt);
            }
        });

        txtTelefPer.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtTelefPer.setForeground(new java.awt.Color(111, 67, 57));
        txtTelefPer.setText("   Telefono");
        txtTelefPer.setBorder(null);
        txtTelefPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefPerActionPerformed(evt);
            }
        });

        txtContra.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtContra.setForeground(new java.awt.Color(111, 67, 57));
        txtContra.setBorder(null);
        txtContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraActionPerformed(evt);
            }
        });

        cmbRol.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbRol.setForeground(new java.awt.Color(111, 67, 57));
        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Vendedor" }));
        cmbRol.setBorder(null);
        cmbRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbRol, 0, 382, Short.MAX_VALUE)
                    .addComponent(txtContra)
                    .addComponent(txtTelefPer)
                    .addComponent(txtEmailPer)
                    .addComponent(txtNomPer)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnCancelarPer, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(btnActualizarPer, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)))
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(txtNomPer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmailPer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTelefPer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarPer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarPer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jp5Layout = new javax.swing.GroupLayout(jp5);
        jp5.setLayout(jp5Layout);
        jp5Layout.setHorizontalGroup(
            jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jp5Layout.setVerticalGroup(
            jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jp4Layout = new javax.swing.GroupLayout(jp4);
        jp4.setLayout(jp4Layout);
        jp4Layout.setHorizontalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
            .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp4Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        jp4Layout.setVerticalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
            .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jp5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jp3Layout = new javax.swing.GroupLayout(jp3);
        jp3.setLayout(jp3Layout);
        jp3Layout.setHorizontalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
            .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp3Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(jp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        jp3Layout.setVerticalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jp4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        btnPersonal.setBackground(new java.awt.Color(111, 67, 57));
        btnPersonal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPersonal.setForeground(new java.awt.Color(253, 231, 195));
        btnPersonal.setText("Personal");
        btnPersonal.setBorder(null);
        btnPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonalActionPerformed(evt);
            }
        });

        btnProductos.setBackground(new java.awt.Color(111, 67, 57));
        btnProductos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(253, 231, 195));
        btnProductos.setText("Productos");
        btnProductos.setBorder(null);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnPedidos.setBackground(new java.awt.Color(111, 67, 57));
        btnPedidos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnPedidos.setForeground(new java.awt.Color(253, 231, 195));
        btnPedidos.setText("Pedidos");
        btnPedidos.setBorder(null);
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });

        btnSalir2.setBackground(new java.awt.Color(246, 199, 129));
        btnSalir2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSalir2.setForeground(new java.awt.Color(253, 231, 195));
        btnSalir2.setText("Salir");
        btnSalir2.setBorder(null);
        btnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir2ActionPerformed(evt);
            }
        });

        btnMasVendidos.setBackground(new java.awt.Color(111, 67, 57));
        btnMasVendidos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnMasVendidos.setForeground(new java.awt.Color(253, 231, 195));
        btnMasVendidos.setText("Ranking");
        btnMasVendidos.setBorder(null);
        btnMasVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasVendidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPersonal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMasVendidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPedidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnMasVendidos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addComponent(jp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonalActionPerformed
        Personal PersonalFrame = new Personal();
        PersonalFrame.setVisible(true);
        PersonalFrame.pack();
        PersonalFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnPersonalActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        ProductoFrame ProductoFrame = new ProductoFrame();
        ProductoFrame.setVisible(true);
        ProductoFrame.pack();
        ProductoFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        PedidoFrame PedidoFrame = new PedidoFrame();
        PedidoFrame.setVisible(true);
        PedidoFrame.pack();
        PedidoFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void btnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir2ActionPerformed
        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnSalir2ActionPerformed

    private void btnMasVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasVendidosActionPerformed
        Menu MenuFrame = new Menu();
        MenuFrame.setVisible(true);
        MenuFrame.pack();
        MenuFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnMasVendidosActionPerformed

    private void btnCancelarPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPerActionPerformed
        Personal PersonalFrame = new Personal();
        PersonalFrame.setVisible(true);
        PersonalFrame.pack();
        PersonalFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnCancelarPerActionPerformed

    private void btnActualizarPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPerActionPerformed
        try {
                String nombre = txtNomPer.getText().trim();
                String email = txtEmailPer.getText().trim();
                String contrasena = txtContra.getText().trim();
                Integer telefono = txtTelefPer.getText().isEmpty() ? null : Integer.parseInt(txtTelefPer.getText().trim());
                String rol = (String) cmbRol.getSelectedItem();

                System.out.println("Actualizando - ID: " + personalId + ", Nombre: " + nombre + ", Email: " + email + 
                                  ", Contraseña: '" + contrasena + "', Teléfono: " + telefono + ", Rol: " + rol);

                // Si la contraseña no se modifica (sigue siendo "contraseña" o vacía), no la validamos ni actualizamos
                if (contrasena.equals("contraseña") || contrasena.isEmpty()) {
                    contrasena = null; // Indica que no se debe cambiar
                } else if (contrasena != null && !Personal.validarContrasena(contrasena)) {
                    JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula y un carácter especial.");
                    return;
                }

                if (personalController.editarPersonal(personalId, nombre, email, contrasena, telefono, rol)) {
                    JOptionPane.showMessageDialog(this, "Personal actualizado exitosamente.");
                    personalFrame.actualizarTabla();
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al actualizar personal. Revisa la consola para más detalles.");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Teléfono debe ser un número válido.");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Ocurrió un error: " + ex.getMessage());
                ex.printStackTrace();
            }
    }//GEN-LAST:event_btnActualizarPerActionPerformed

    
    
    
    private void txtNomPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomPerActionPerformed
    }//GEN-LAST:event_txtNomPerActionPerformed

    private void cmbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRolActionPerformed

    private void txtNomPerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomPerMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomPerMouseDragged

    private void txtContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraActionPerformed

    private void txtTelefPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefPerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefPerActionPerformed

    private void txtEmailPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailPerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailPerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPersonal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarPersonal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarPer;
    private javax.swing.JButton btnCancelarPer;
    private javax.swing.JButton btnMasVendidos;
    private javax.swing.JButton btnPedidos;
    private javax.swing.JButton btnPersonal;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnSalir2;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jp3;
    private javax.swing.JPanel jp4;
    private javax.swing.JPanel jp5;
    private javax.swing.JTextField txtContra;
    private javax.swing.JTextField txtEmailPer;
    private javax.swing.JTextField txtNomPer;
    private javax.swing.JTextField txtTelefPer;
    // End of variables declaration//GEN-END:variables
}
